### ISSUE TITLE
Is the project alive at all?

### ISSUE THREAD

**Issue by Kzer-Za** [liflg/docs#1]
At least some documentation would be nice to have. And the mailbox at team@liflg.org is unreachable: `Quota exceeded (mailbox for user is full)`

**Comment by kratz00** [comment]
Hi @Kzer-Za 

We got your mail (only one of the email list recipient's mail box is full).
What documentation are you looking for? What are you trying to achieve?

**Comment by Kzer-Za** [comment]
Ah, sorry then. I am trying to compile the installer for Unreal Tournament.

**Comment by kratz00** [comment]
https://github.com/liflg/unreal.tournament_451-english_x86/ <- That one?

Get and compile mojosetup:
```
hg clone https://hg.icculus.org/icculus/mojosetup
wget https://liflg.org/fix_translations.patch
patch mojosetup/scripts/localization.lua fix_translations.patch
mkdir mojosetup/build
cd mojosetup/build
cmake ..
make -j $(nproc) skeleton
```

Get the UT installer and copy its data into the skeleton directory and run the installer:
```
git clone https://github.com/liflg/unreal.tournament_451-english_x86.git
cp -pr unreal.tournament_451-english_x86/* skeleton/
cd skeleton
./mojosetup
```

**Comment by Kzer-Za** [comment]
Thanks! :)

That's what I was talking about, this piece of information probably should be in the documentation.

**Comment by kratz00** [comment]
Pull requests are always welcome :smile:

**Comment by kratz00** [comment]
FYI, the patch is not needed anymore, it was up-streamed: https://hg.icculus.org/icculus/mojosetup/rev/d988d804737f
