### ISSUE TITLE
UT99GOTY Disc 2 not recognized

### ISSUE THREAD

**Issue by LuxDaemon** [liflg/docs#2]
I've inserted disc 2 of UT99 but it's not recognized by the Mojo installer. It keeps telling me to insert disc 2 even if I've already mounted it.

**Comment by kratz00** [comment]
The installer is looking for a file called *UnrealEd/UnrealEdInstaller.exe* on the disc, see https://github.com/liflg/unreal.tournament_451-english_x86/blob/master/scripts/config.lua#L50
Does it exist?

**Comment by LuxDaemon** [comment]
It does not... Maybe I'm using the wrong images... Thanks for the info.
